package ar.com.bia.dto.jstree;


/**
 * http://www.jstree.com/docs/json/
 // Expected format of the node (there are no required fields)
{
  id          : "string" // will be autogenerated if omitted
  text        : "string" // node text
  icon        : "string" // string for custom
  state       : {
    opened    : boolean  // is the node open
    disabled  : boolean  // is the node disabled
    selected  : boolean  // is the node selected
  },
  children    : boolean  // if it has any children
  li_attr     : {}  // attributes for the generated LI node
  a_attr      : {}  // attributes for the generated A node
}
 */
public class JSTreeNodeAjax extends JSTreeNodeAbstract {

	
	
	public JSTreeNodeAjax() {
		super();	
	}

	private boolean children;

	public boolean isChildren() {
		return children;
	}

	public void setChildren(boolean children) {
		this.children = children;
	}
	

	
	
}
